//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace StartPro.Resources {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Main {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Main() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("StartPro.Resources.Main", typeof(Main).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 取消 的本地化字符串。
        /// </summary>
        public static string CancelText {
            get {
                return ResourceManager.GetString("CancelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 添加新的磁贴 的本地化字符串。
        /// </summary>
        public static string CreatTitle {
            get {
                return ResourceManager.GetString("CreatTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 确定 的本地化字符串。
        /// </summary>
        public static string OkText {
            get {
                return ResourceManager.GetString("OkText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 大 的本地化字符串。
        /// </summary>
        public static string SizeLarge {
            get {
                return ResourceManager.GetString("SizeLarge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 中 的本地化字符串。
        /// </summary>
        public static string SizeMid {
            get {
                return ResourceManager.GetString("SizeMid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 小 的本地化字符串。
        /// </summary>
        public static string SizeSmall {
            get {
                return ResourceManager.GetString("SizeSmall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 宽 的本地化字符串。
        /// </summary>
        public static string SizeWide {
            get {
                return ResourceManager.GetString("SizeWide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 字号:  的本地化字符串。
        /// </summary>
        public static string TileFontSizeText {
            get {
                return ResourceManager.GetString("TileFontSizeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 图标:  的本地化字符串。
        /// </summary>
        public static string TileIconText {
            get {
                return ResourceManager.GetString("TileIconText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 名称:  的本地化字符串。
        /// </summary>
        public static string TileNameText {
            get {
                return ResourceManager.GetString("TileNameText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 路径: 的本地化字符串。
        /// </summary>
        public static string TilePathText {
            get {
                return ResourceManager.GetString("TilePathText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 尺寸: 的本地化字符串。
        /// </summary>
        public static string TileSizeText {
            get {
                return ResourceManager.GetString("TileSizeText", resourceCulture);
            }
        }
    }
}
