//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace StartPro.Resources {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Main {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Main() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("StartPro.Resources.Main", typeof(Main).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 Background: 的本地化字符串。
        /// </summary>
        public static string BackgroundText {
            get {
                return ResourceManager.GetString("BackgroundText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Cancel 的本地化字符串。
        /// </summary>
        public static string CancelText {
            get {
                return ResourceManager.GetString("CancelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Add Tile 的本地化字符串。
        /// </summary>
        public static string CreateTileTitle {
            get {
                return ResourceManager.GetString("CreateTileTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Edit Tile 的本地化字符串。
        /// </summary>
        public static string EditTileTitle {
            get {
                return ResourceManager.GetString("EditTileTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 OK 的本地化字符串。
        /// </summary>
        public static string OkText {
            get {
                return ResourceManager.GetString("OkText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Select Color 的本地化字符串。
        /// </summary>
        public static string SelectColorText {
            get {
                return ResourceManager.GetString("SelectColorText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 High 的本地化字符串。
        /// </summary>
        public static string SizeHigh {
            get {
                return ResourceManager.GetString("SizeHigh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Large 的本地化字符串。
        /// </summary>
        public static string SizeLarge {
            get {
                return ResourceManager.GetString("SizeLarge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Medium 的本地化字符串。
        /// </summary>
        public static string SizeMid {
            get {
                return ResourceManager.GetString("SizeMid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Small 的本地化字符串。
        /// </summary>
        public static string SizeSmall {
            get {
                return ResourceManager.GetString("SizeSmall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Wide 的本地化字符串。
        /// </summary>
        public static string SizeWide {
            get {
                return ResourceManager.GetString("SizeWide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Color: 的本地化字符串。
        /// </summary>
        public static string TileColorText {
            get {
                return ResourceManager.GetString("TileColorText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Delete 的本地化字符串。
        /// </summary>
        public static string TileContextDelete {
            get {
                return ResourceManager.GetString("TileContextDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Edit 的本地化字符串。
        /// </summary>
        public static string TileContextEdit {
            get {
                return ResourceManager.GetString("TileContextEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Open file location 的本地化字符串。
        /// </summary>
        public static string TileContextOpen {
            get {
                return ResourceManager.GetString("TileContextOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Run as Administrator 的本地化字符串。
        /// </summary>
        public static string TileContextRunAs {
            get {
                return ResourceManager.GetString("TileContextRunAs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Font Size: 的本地化字符串。
        /// </summary>
        public static string TileFontSizeText {
            get {
                return ResourceManager.GetString("TileFontSizeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Icon: 的本地化字符串。
        /// </summary>
        public static string TileIconText {
            get {
                return ResourceManager.GetString("TileIconText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Image Shadow 的本地化字符串。
        /// </summary>
        public static string TileImageShadowText {
            get {
                return ResourceManager.GetString("TileImageShadowText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Name: 的本地化字符串。
        /// </summary>
        public static string TileNameText {
            get {
                return ResourceManager.GetString("TileNameText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Path: 的本地化字符串。
        /// </summary>
        public static string TilePathText {
            get {
                return ResourceManager.GetString("TilePathText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Tile Shadow 的本地化字符串。
        /// </summary>
        public static string TileShadowText {
            get {
                return ResourceManager.GetString("TileShadowText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Size: 的本地化字符串。
        /// </summary>
        public static string TileSizeText {
            get {
                return ResourceManager.GetString("TileSizeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Exit 的本地化字符串。
        /// </summary>
        public static string TrayExit {
            get {
                return ResourceManager.GetString("TrayExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Show/Hide 的本地化字符串。
        /// </summary>
        public static string TrayShowHide {
            get {
                return ResourceManager.GetString("TrayShowHide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Default theme for Windows Vista/7 的本地化字符串。
        /// </summary>
        public static string UITheme_Aero_NormalColor {
            get {
                return ResourceManager.GetString("UITheme.Aero.NormalColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Default theme for Windows 8/8.1/10 的本地化字符串。
        /// </summary>
        public static string UITheme_Aero2_NormalColor {
            get {
                return ResourceManager.GetString("UITheme.Aero2.NormalColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Default theme for Windows 9x series 的本地化字符串。
        /// </summary>
        public static string UITheme_Classic {
            get {
                return ResourceManager.GetString("UITheme.Classic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Olive theme for Windows XP 的本地化字符串。
        /// </summary>
        public static string UITheme_Luna_Homestead {
            get {
                return ResourceManager.GetString("UITheme.Luna.Homestead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Silver theme for Windows XP 的本地化字符串。
        /// </summary>
        public static string UITheme_Luna_Metallic {
            get {
                return ResourceManager.GetString("UITheme.Luna.Metallic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Default blue theme for Windows XP 的本地化字符串。
        /// </summary>
        public static string UITheme_Luna_NormalColor {
            get {
                return ResourceManager.GetString("UITheme.Luna.NormalColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Media Center theme for Windows XP 的本地化字符串。
        /// </summary>
        public static string UITheme_Royale_NormalColor {
            get {
                return ResourceManager.GetString("UITheme.Royale.NormalColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 UI Theme: 的本地化字符串。
        /// </summary>
        public static string UIThemeText {
            get {
                return ResourceManager.GetString("UIThemeText", resourceCulture);
            }
        }
    }
}
