//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace StartPro.Resources {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class TextConfigure {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TextConfigure() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("StartPro.Resources.TextConfigure", typeof(TextConfigure).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 Color:  的本地化字符串。
        /// </summary>
        public static string ColorText {
            get {
                return ResourceManager.GetString("ColorText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Font Family:  的本地化字符串。
        /// </summary>
        public static string FontFamilyText {
            get {
                return ResourceManager.GetString("FontFamilyText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Font Size:  的本地化字符串。
        /// </summary>
        public static string FontSizeText {
            get {
                return ResourceManager.GetString("FontSizeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Condensed 的本地化字符串。
        /// </summary>
        public static string FontStretchCondensed {
            get {
                return ResourceManager.GetString("FontStretchCondensed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Expanded 的本地化字符串。
        /// </summary>
        public static string FontStretchExpanded {
            get {
                return ResourceManager.GetString("FontStretchExpanded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ExtraCondensed 的本地化字符串。
        /// </summary>
        public static string FontStretchExtraCondensed {
            get {
                return ResourceManager.GetString("FontStretchExtraCondensed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ExtraExpanded 的本地化字符串。
        /// </summary>
        public static string FontStretchExtraExpanded {
            get {
                return ResourceManager.GetString("FontStretchExtraExpanded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Normal 的本地化字符串。
        /// </summary>
        public static string FontStretchNormal {
            get {
                return ResourceManager.GetString("FontStretchNormal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 SemiCondensed 的本地化字符串。
        /// </summary>
        public static string FontStretchSemiCondensed {
            get {
                return ResourceManager.GetString("FontStretchSemiCondensed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 SemiExpanded 的本地化字符串。
        /// </summary>
        public static string FontStretchSemiExpanded {
            get {
                return ResourceManager.GetString("FontStretchSemiExpanded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Font Stretch:  的本地化字符串。
        /// </summary>
        public static string FontStretchText {
            get {
                return ResourceManager.GetString("FontStretchText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 UltraCondensed 的本地化字符串。
        /// </summary>
        public static string FontStretchUltraCondensed {
            get {
                return ResourceManager.GetString("FontStretchUltraCondensed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 UltraExpanded  的本地化字符串。
        /// </summary>
        public static string FontStretchUltraExpanded {
            get {
                return ResourceManager.GetString("FontStretchUltraExpanded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Italic 的本地化字符串。
        /// </summary>
        public static string FontStyleItalic {
            get {
                return ResourceManager.GetString("FontStyleItalic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Normal 的本地化字符串。
        /// </summary>
        public static string FontStyleNormal {
            get {
                return ResourceManager.GetString("FontStyleNormal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Oblique 的本地化字符串。
        /// </summary>
        public static string FontStyleOblique {
            get {
                return ResourceManager.GetString("FontStyleOblique", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Font Style:  的本地化字符串。
        /// </summary>
        public static string FontStyleText {
            get {
                return ResourceManager.GetString("FontStyleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Bold 的本地化字符串。
        /// </summary>
        public static string FontWeightBold {
            get {
                return ResourceManager.GetString("FontWeightBold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Heavy 的本地化字符串。
        /// </summary>
        public static string FontWeightHeavy {
            get {
                return ResourceManager.GetString("FontWeightHeavy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Light 的本地化字符串。
        /// </summary>
        public static string FontWeightLight {
            get {
                return ResourceManager.GetString("FontWeightLight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Medium 的本地化字符串。
        /// </summary>
        public static string FontWeightMedium {
            get {
                return ResourceManager.GetString("FontWeightMedium", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Normal 的本地化字符串。
        /// </summary>
        public static string FontWeightNormal {
            get {
                return ResourceManager.GetString("FontWeightNormal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Font Weight:  的本地化字符串。
        /// </summary>
        public static string FontWeightText {
            get {
                return ResourceManager.GetString("FontWeightText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Thin 的本地化字符串。
        /// </summary>
        public static string FontWeightThin {
            get {
                return ResourceManager.GetString("FontWeightThin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Center 的本地化字符串。
        /// </summary>
        public static string TextAlignmentCenter {
            get {
                return ResourceManager.GetString("TextAlignmentCenter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Justify 的本地化字符串。
        /// </summary>
        public static string TextAlignmentJustify {
            get {
                return ResourceManager.GetString("TextAlignmentJustify", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Left 的本地化字符串。
        /// </summary>
        public static string TextAlignmentLeft {
            get {
                return ResourceManager.GetString("TextAlignmentLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Right 的本地化字符串。
        /// </summary>
        public static string TextAlignmentRight {
            get {
                return ResourceManager.GetString("TextAlignmentRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Text Alignment:  的本地化字符串。
        /// </summary>
        public static string TextAlignmentText {
            get {
                return ResourceManager.GetString("TextAlignmentText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Text Configure 的本地化字符串。
        /// </summary>
        public static string TextConfigureText {
            get {
                return ResourceManager.GetString("TextConfigureText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Baseline 的本地化字符串。
        /// </summary>
        public static string TextDecorationBaseline {
            get {
                return ResourceManager.GetString("TextDecorationBaseline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 OverLine 的本地化字符串。
        /// </summary>
        public static string TextDecorationOverLine {
            get {
                return ResourceManager.GetString("TextDecorationOverLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Strikethrough 的本地化字符串。
        /// </summary>
        public static string TextDecorationStrikethrough {
            get {
                return ResourceManager.GetString("TextDecorationStrikethrough", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Text Decorations:  的本地化字符串。
        /// </summary>
        public static string TextDecorationText {
            get {
                return ResourceManager.GetString("TextDecorationText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Underline 的本地化字符串。
        /// </summary>
        public static string TextDecorationUnderline {
            get {
                return ResourceManager.GetString("TextDecorationUnderline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Text Effect:  的本地化字符串。
        /// </summary>
        public static string TextEffectText {
            get {
                return ResourceManager.GetString("TextEffectText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Text Shadow 的本地化字符串。
        /// </summary>
        public static string TextShadowText {
            get {
                return ResourceManager.GetString("TextShadowText", resourceCulture);
            }
        }
    }
}
