//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace StartPro.Resources {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Tile {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Tile() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("StartPro.Resources.Tile", typeof(Tile).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 Color: 的本地化字符串。
        /// </summary>
        public static string ColorText {
            get {
                return ResourceManager.GetString("ColorText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Delete 的本地化字符串。
        /// </summary>
        public static string ContextDelete {
            get {
                return ResourceManager.GetString("ContextDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Edit 的本地化字符串。
        /// </summary>
        public static string ContextEdit {
            get {
                return ResourceManager.GetString("ContextEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Change Size 的本地化字符串。
        /// </summary>
        public static string ContextFastChange {
            get {
                return ResourceManager.GetString("ContextFastChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Font Size: 的本地化字符串。
        /// </summary>
        public static string FontSizeText {
            get {
                return ResourceManager.GetString("FontSizeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Tile Shadow 的本地化字符串。
        /// </summary>
        public static string ShadowText {
            get {
                return ResourceManager.GetString("ShadowText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 High 的本地化字符串。
        /// </summary>
        public static string SizeHigh {
            get {
                return ResourceManager.GetString("SizeHigh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Large 的本地化字符串。
        /// </summary>
        public static string SizeLarge {
            get {
                return ResourceManager.GetString("SizeLarge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Medium 的本地化字符串。
        /// </summary>
        public static string SizeMedium {
            get {
                return ResourceManager.GetString("SizeMedium", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Small 的本地化字符串。
        /// </summary>
        public static string SizeSmall {
            get {
                return ResourceManager.GetString("SizeSmall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Tall 的本地化字符串。
        /// </summary>
        public static string SizeTall {
            get {
                return ResourceManager.GetString("SizeTall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Size: 的本地化字符串。
        /// </summary>
        public static string SizeText {
            get {
                return ResourceManager.GetString("SizeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Thin 的本地化字符串。
        /// </summary>
        public static string SizeThin {
            get {
                return ResourceManager.GetString("SizeThin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Wide 的本地化字符串。
        /// </summary>
        public static string SizeWide {
            get {
                return ResourceManager.GetString("SizeWide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Add Tile 的本地化字符串。
        /// </summary>
        public static string TitleCreate {
            get {
                return ResourceManager.GetString("TitleCreate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Edit Tile 的本地化字符串。
        /// </summary>
        public static string TitleEdit {
            get {
                return ResourceManager.GetString("TitleEdit", resourceCulture);
            }
        }
    }
}
