name: .NET Build

on:
  push:
    branches: ["master"]

  pull_request:
    branches: ["master"]

jobs:
  build:
    strategy:
      matrix:
        configuration: [Debug, Release]

    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install .NET
        uses: actions/setup-dotnet@v4

      - name: Build Solution
        run: dotnet build --configuration $env:Configuration
        env:
          Configuration: ${{ matrix.configuration }}

      - name: Upload Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.configuration }}
          path: ./StartPro/bin/${{ matrix.configuration }}/net452/*