name: .NET Build

on:
  push:
    branches: ["main"]

  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - name: Install .NET
        uses: actions/setup-dotnet@v6

      - name: Publish EasyStart
        run: dotnet publish -p:PublishProfile=FolderProfile -c Release

      - name: Upload EasyStart
        uses: actions/upload-artifact@v7
        with:
          name: EasyStart
          path: ./StartPro/bin/publish/*

      - name: Publish EasyStart with runtime
        run: dotnet publish -p:PublishProfile=FolderProfile -c Release --self-contained

      - name: Upload EasyStart with runtime
        uses: actions/upload-artifact@v7
        with:
          name: EasyStart-with-runtime
          path: ./StartPro/bin/publish/*
